-- Material You — colors are dynamically generated by matugen
-- This is a placeholder; a matugen hook should overwrite this file.
return {
  bg0 = "rgba(1c1c1eff)",
  bg1 = "rgba(2c2c2eff)",
  bg2 = "rgba(3a3a3cff)",
  bg3 = "rgba(48484aff)",
  bg4 = "rgba(555557ff)",
  fg = "rgba(f2f2f7ff)",
  red    = "rgba(ff453aff)",
  orange = "rgba(ff9f0aff)",
  yellow = "rgba(ffd60aff)",
  green  = "rgba(30d158ff)",
  aqua   = "rgba(66d4cfff)",
  blue   = "rgba(0a84ffff)",
  purple = "rgba(bf5af2ff)",
  grey0  = "rgba(636366ff)",
  grey1  = "rgba(8e8e93ff)",
  grey2  = "rgba(aeb5c0ff)",
}
